# Uncomment the next line to define a global platform for your project
platform :ios, '11.0' # Update the platform version to at least iOS 11.0, as recommended for the latest AdMob SDK

target 'Barcodes_JS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Barcodes_JS
  pod 'Google-Mobile-Ads-SDK'

  target 'Barcodes_JSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Barcodes_JSUITests' do
    # Pods for testing
  end

end
